spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sky?useSSL=false&serverTimezone=UTC
    username: root
    password: zzy123
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: 192.168.152.129
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: 123

  redis:
    host: localhost
    password: 123456
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

mybatis-plus:
#  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.young.sky.Entity

logging:
  level:
    com.young.sky: debug
    org.springframework.web: debug